<script lang="ts">
  /**
   * What's behind the doors — the actual app, shown to someone who can't open them yet.
   *
   * Real screenshots of Explore, Discover and a game page, taken from the running app. Not
   * a chart from content.json, not an illustration: the product's own pixels. A logged-out
   * visitor sees the chips above and can read what they could ask; this is what an answer
   * looks like. Each frame is a door into the same room, via /login?next=.
   *
   * Logged-out only. For a member this is dead weight — they use the app — and the warm gap
   * takes this slot for them instead.
   *
   * Light and dark captures, swapped on mode-watcher's `.dark` class, so the frame matches
   * the page around it rather than glowing white in a dark theme. The files live in
   * static/landing/ and are regenerated by hand when the app's look changes.
   *
   * Copy is PLACEHOLDER — Phil writes the final strings.
   */
  let { gate }: { gate: (url: string) => string } = $props();

  // PLACEHOLDER copy
  const shots = [
    {
      key: 'explore',
      title: 'Explore',
      blurb: 'Filter the whole catalog down to a set, see its shape, sort it, drill in.',
      href: '/games?wmin=3.5&ymin=2015',
      alt: 'Explore: 826 heavyweight games since 2015, with distribution charts for rating, complexity, year and player count above a sortable table.'
    },
    {
      key: 'discover',
      title: 'Discover',
      blurb: 'Answer a few questions, get a shortlist.',
      href: '/discover?best=4&mechs=Cooperative+Game',
      alt: 'Discover: cooperative games best at 4 players, narrowed to 481 matches with a ranked list.'
    },
    {
      key: 'game',
      title: 'Every game, in depth',
      blurb: 'Ratings, player counts as the community voted, and the games most like it.',
      href: '/games/224517',
      alt: 'The game page for Brass: Birmingham, with ratings, categories, mechanics and a Similar Games panel.'
    }
  ];
</script>

<section class="show" aria-label="What you'll see">
  {#each shots as s (s.key)}
    <a class="frame" href={gate(s.href)}>
      <div class="cap">
        <span class="t">{s.title} <span class="arw">→</span></span>
        <span class="b">{s.blurb}</span>
      </div>
      <img class="light" src="/landing/{s.key}-light.webp" alt={s.alt} loading="lazy" width="1440" height="896" />
      <img class="dark"  src="/landing/{s.key}-dark.webp"  alt="" aria-hidden="true" loading="lazy" width="1440" height="896" />
    </a>
  {/each}
</section>

<style>
  .show { display: flex; flex-direction: column; gap: clamp(2rem, 4vw, 3.5rem); }

  .frame { display: flex; flex-direction: column; gap: .7rem; text-decoration: none; color: inherit; }
  .cap { display: flex; flex-direction: column; gap: .15rem; }
  .t { font-size: 1.05rem; font-weight: 700; letter-spacing: -0.01em; color: var(--primary); }
  .arw { opacity: .7; }
  .b { font-size: .92rem; color: var(--muted-foreground); }

  img { display: block; width: 100%; height: auto; border: 1px solid var(--border); border-radius: var(--radius); background: var(--card);
    box-shadow: 0 1px 2px color-mix(in oklch, var(--foreground) 6%, transparent), 0 8px 24px -12px color-mix(in oklch, var(--foreground) 25%, transparent); }
  .frame:hover img { border-color: var(--primary); }

  /* One capture per theme; mode-watcher puts `.dark` on <html>. */
  img.dark { display: none; }
  :global(.dark) img.light { display: none; }
  :global(.dark) img.dark { display: block; }
</style>
